### ISSUE TITLE
Unable to pull image in from pipelines

### ISSUE THREAD

**Issue by robert-lilleker** [aquasecurity/trivy-pipe#3]
When I use the the pipe I get the following: "It looks like you tried to use a pipe in your bitbucket-pipelines.yml that doesn’t exist. Check the name of the pipe and try again." 

Here is the pipeline below:

```
- pipe: aquasec/trivy-pipe:latest
   variables:
     imageRef: <account>.dkr.ecr.region.amazonaws.com/reverse-proxy-federal:${BITBUCKET_COMMIT}
     format: template
     template: '@/contrib/sarif.tpl'
     output: trivy-results.sarif
     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
     AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
```
